assets/CSS/select.css
assets/CSS/style.css
assets/js/select.js
index.html

I fixed the fetch Pokemon list function. It now works with a handmade loop of a single function that calls itself each time. I also added other functions that will be called after the fetch to render the pokemons. Lastly, I added more styling to the index.html. The left PokeCard is now finished.

debuged the fetch and added further style

---

assets/js/drink.js
assets/js/select.js

Local Storage cuando el usuario da click en "Select"

Local Storage del Pokemon Central

---

assets/CSS/select.css
assets/CSS/style.css
assets/js/select.js
index.html

I added the scroller feature for the Pokemon showroom. The Pokemons now change position, and the left card fills up with their data. The color theme for both left and right cards changes depending on the poke-type.

added the scroller feature to the site

---

assets/js/drink.js
assets/js/select.js
drink.html

Conectar drink html con su js y mostrar en el console log el dato guardado del usuario en la pagina anterior.
Adicional, ya redirecciona a la segunda página

Agregar local Storage a segunda pagina

---

assets/js/select.js

debugged pokemon local storage function because the target elements were wrong

pokemon local storage function debugged

---

assets/js/select.js

turned the pokemon local storage into a function, called it with the eventListener and testing drinks fetch

turned the pokemon local storage into a function and drinks fetch

---

assets/js/select.js

I added some comments and the object to define the drink fetch parameters.

added poke-type/drink relation object

---

drink.html

Started writing the html for the drinks

Starting the drinks html

---

assets/CSS/select.css
assets/js/logic.js
assets/js/select.js
index.html

I added a triple fetch based on the Pokemon types: if two types/ingredients don't return a response, it tries with only the first type. Then, the code fetches the drinks from the list, checking each time if the drink is alcoholic or not, and it continues to fetch until an alcoholic drink is found.

added drink fetch based on poketype, added poke row changer, added rendering data

---

assets/CSS/style.css
assets/js/select.js
index.html

The select button now changes to drink.html while storing in local the selected pokeDrink to be then used in the drink page.

added select btn listener to save in local and change page

---

assets/js/select.js
drink.html

added 2 sections on the drinks html

added the sections and adjust the width sizes to 1/3 and 2/3

---

assets/CSS/select.css
assets/CSS/style.css
assets/js/drink.js
assets/js/logic.js
assets/js/select.js
index.html

The mobile version for index.html is ready. I added a bunch of additional media queries.
The Booze-Dex is in progress; design-wise, it's done, but rendering is still needed.

added mobile versión for index. Booze dex is in progress.

---

assets/CSS/drink.css
assets/js/drink.js
drink.html

finished the drinks page sketch, starting the styles and creating the functions to extract data from the local storage

finished the drinks html, starting styles and js

---

assets/js/drink.js
drink.html

Optimized some functions to extract info from local storage and render it on the page

rendering info from localstorage

---

assets/js/drink.js
drink.html

optimized some functions, added a function to render the drink's name and save the info from pokemon and drink in local storage

optimizing functions and save local storage

---

assets/js/drink.js
drink.html

-Debugged RenderInstructions functions to add "of" only if the last word is not "of" or "with"
-Added the save button
-Styling the button and the entire div

debug ingredients function and added styles

---

assets/CSS/select.css
assets/CSS/style.css
assets/js/drink.js
assets/js/logic.js
assets/js/select.js
index.html

I finished the Booze-Dex; it now saves all the favorite poke drinks and allows you to delete and select any of them.

finished the booze-dex along with the drink.js save drink

---

assets/CSS/drink.css
assets/CSS/style.css
assets/js/drink.js
drink.html

making the drinks page responsive for smaller screens and debugged the footer

mobile design for drinks

---

drink.html

debugged drinks footer and made it responsive

Footerdebugv2

---

assets/js/select.js
index.html

I debugged poke-drinks rendering when the gif didn't exist. I also cleaned the code a little.

debugged poke-drinks rendering when the gif didn't exist
